# E-COMMERCE SALES ANALYSIS
# Dataset: Approximately 500 records and 11 columns

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. LOAD THE DATASET
# The index_col parameter can be used to set a specific column
# as the DataFrame index.
# Example:
# data = pd.read_excel("sales_dataset.xlsx", index_col="Order_ID")

data = pd.read_excel("sales_dataset.xlsx")
# Display the loaded data
# print(data)

# Convert the loaded data into a Pandas DataFrame
df = pd.DataFrame(data)
# print(df)

# 2. UNDERSTANDING THE DATA

# Display basic information about the dataset
print(df.info())

# Display statistical summary of numerical columns
print(df.describe())

# Returns the number of rows and columns
print(df.shape)

# Display the first five rows
print(df.head())

# Display the last five rows
print(df.tail())

# Display all column names
print(df.columns)

# Display the frequency of unique row combinations
# print(df.value_counts())


# 3. DATA CLEANING

# Check for missing values in each column
print(df.isnull().sum())


# Check for duplicate rows
print("Duplicates:", df.duplicated().sum())


# Remove duplicate rows from the dataset
df = df.drop_duplicates()


# Convert the Order_Date column into Pandas datetime format
df["Order_Date"] = pd.to_datetime(df["Order_Date"])


# Check the data types of all columns
print(df.dtypes)


# 4. TOTAL REVENUE
# Calculate the total revenue generated from all sales
total_revenue = df["Sales"].sum()

print("Total Revenue:", total_revenue)


# 5. TOTAL ORDERS

# Count the number of unique orders.
# nunique() is used because one order can potentially contain
# multiple products or multiple rows in the dataset.

total_orders = df["Order_ID"].nunique()

print(f"Total Orders: {total_orders}")


# 6. AVERAGE ORDER VALUE (AOV)
# Calculate the average amount of revenue generated per order.
# Business meaning:
# AOV tells us how much money the company makes, on average,
# from one customer order.

average_order_value = total_revenue / total_orders

print(f"Average Order Value: {average_order_value}")


# 7. MONTHLY REVENUE TREND
# Create a new Month column from the Order_Date column.
# The "M" period represents the month.

df["Month"] = df["Order_Date"].dt.to_period("M")


# .dt provides access to datetime properties and functions.
# .to_period("M") converts each date into a monthly period.
# Example:
# 2024-05-15 -> 2024-05
# 2024-05-30 -> 2024-05 
# This is useful when grouping and aggregating sales
# month-wise without considering the exact day.
# Common frequency strings used with to_period():
# "M" -> Month
# "Q" -> Quarter
# "Y" -> Year
# "D" -> Day


# Group sales by month and calculate total sales for each month.
monthly_sales = df.groupby("Month")["Sales"].sum()

print(monthly_sales)


# -------------------- Monthly Sales Visualization --------------------

# Create a line chart to visualize monthly revenue trends.
monthly_sales.plot(kind="line", marker="o")

plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
# Rotate x-axis labels by 45 degrees to improve readability.
plt.xticks(rotation=45)
# Automatically adjust the layout to prevent overlapping elements.
plt.tight_layout()
# Display the chart.
plt.show()


# 8. TOP 10 PRODUCTS BY SALES

# Group sales by Product.
# Calculate total sales for each product.
# Sort products from highest sales to lowest sales.
# Select the top 10 products.

top_products = (df.groupby("Product")["Sales"].sum().sort_values(ascending=False).head(10))

print(top_products)

# Create a bar chart showing the top 10 products by sales.

top_products.plot(kind="bar")

plt.figure(figsize=(10, 5))
plt.bar(top_products.index.astype(str), top_products.values)

plt.title("Top 10 Products by Sales")
plt.xlabel("Product")
plt.ylabel("Sales")

# Rotate product names for better readability.
plt.xticks(rotation=45)

# Automatically adjust the layout.
plt.tight_layout()

# Display the chart.
plt.show()


# 9. SALES BY CATEGORY

# Group sales by product category and calculate
# the total sales generated by each category.

category_sales = df.groupby("Category")["Sales"].sum()

print(category_sales)


# Business question:
# Which product category generates the most revenue?
# Create a bar chart to compare sales across categories.

category_sales.plot(kind="bar")

plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")

# Rotate category names for better readability.
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# 10. SALES BY REGION
# Group sales by region.
# Calculate total sales for each region.
# Sort the results from highest sales to lowest sales.

region_sales = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

print(region_sales)


# Create a pie chart to show the percentage distribution
# of sales across different regions.

region_sales.plot(kind="pie",autopct="%1.1f%%")

# plt.title("Region Sales Distribution")
# plt.show()


# 11. MOST POPULAR PAYMENT METHOD
# Count how many transactions were made using each
# payment method.

payment_count = df["Payment_Method"].value_counts()

print(payment_count)


# Create a bar chart showing the number of transactions
# for each payment method.

payment_count.plot(kind="bar")

plt.title("Popular Payment Methods")
plt.xlabel("Payment Method")
plt.ylabel("Number of Transactions")

# Rotate payment method names for better readability.
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# 12. HIGHEST SALES MONTH
# idxmax() returns the index/label where the maximum value occurs.

highest_month = monthly_sales.idxmax()

# max() returns the highest sales value.
highest_sales = monthly_sales.max()

print(f"Highest Sales Month: {highest_month}")
print(f"Highest Sales: {highest_sales}")


# 13. LOWEST SALES MONTH
# idxmin() returns the index/label where the minimum value occurs.

lowest_month = monthly_sales.idxmin()

# min() returns the lowest sales value.
lowest_sales = monthly_sales.min()

print(f"Lowest Sales Month: {lowest_month}")
print(f"Lowest Sales: {lowest_sales}")


# 14. DISCOUNT VS SALES CORRELATION

# Calculate the correlation between Discount and Sales.
# Correlation shows the strength and direction of the
# relationship between two numerical variables.
# The value generally ranges from -1 to +1:
# +1  -> Strong positive relationship
#  0  -> No linear relationship
# -1  -> Strong negative relationship

correlation = df["Discount"].corr(df["Sales"])

print(f"Discount-Sales Correlation: {correlation}")


# Create a scatter plot to visually analyze the relationship
# between discount percentage/value and sales.

plt.scatter(df["Discount"], df["Sales"])

plt.title("Discount vs Sales")
plt.xlabel("Discount")
plt.ylabel("Sales")

plt.show()


# 15. NUMPY STATISTICAL ANALYSIS
# Select the Sales column for numerical/statistical analysis.
sales = df["Sales"]
# Mean represents the average sales value.
mean_sales = np.mean(sales)
# Median represents the middle value when all sales values
# are arranged in ascending order.

median_sales = np.median(sales)

# Standard deviation measures how much the sales values
# vary or spread around the mean.

std_sales = np.std(sales)

# 16. PERCENTILE ANALYSIS

# Percentiles divide the dataset into different percentage levels.
#
# Q25 -> 25% of sales values are below this value.
# Q50 -> 50% of sales values are below this value.
# Q75 -> 75% of sales values are below this value.

q25 = np.percentile(sales, 25)
q50 = np.percentile(sales, 50)
q75 = np.percentile(sales, 75)


# Display statistical results

print(f"Mean: {mean_sales}")
print(f"Median: {median_sales}")
print(f"Standard Deviation: {std_sales}")
print(f"25th Percentile: {q25}")
print(f"50th Percentile: {q50}")
print(f"75th Percentile: {q75}")


# 17. OUTLIER ANALYSIS USING IQR METHOD

# IQR stands for Interquartile Range.
# The IQR method is used to identify outliers in the dataset.
# An outlier is a data value that is significantly different
# from the majority of observations.
# Outlier analysis helps identify:
# - Unusually high transactions
# - Unusually low transactions
# - Possible data entry errors
# - Exceptional business transactions
# IQR represents the spread of the middle 50% of the data.

IQR = q75 - q25


# Calculate the lower boundary for identifying outliers.
# Values below this boundary are considered potential
# lower-side outliers.

lower_bouund = q25 - 1.5 * IQR


# Calculate the upper boundary for identifying outliers.
# Values above this boundary are considered potential
# upper-side outliers.

upper_bound = q75 + 1.5 * IQR


# Identify rows where Sales are outside the calculated boundaries.
# "|" represents OR.
# Therefore:
# Sales < Lower Bound
# OR
# Sales > Upper Bound
# These records are treated as potential outliers.

outliers = df[(sales < lower_bouund) | (sales > upper_bound)]

# Display the IQR boundaries and number of detected outliers.

print(f"Lower Bound: {lower_bouund}")
print(f"Upper Bound: {upper_bound}")
print(f"Number of Outliers: {len(outliers)}")